name: GA-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, and macOS

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        node: [12]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: NPM Install and Build
    - run: npm install
    - run: npm run vscode:prepublish
    - name: Run Unit tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test --silent
    - name: Run UI tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run ui-test
    - name: Archiving test artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: test-artifacts
        path: |
          test-resources/screenshots/*.png
          test-resources/*.log
        retention-days: 3
